FROM eclipse-temurin:11-jre-alpine

ENV PORT=9003
ENV DB_PORT=3306
ENV DB_NAME=ThriveX
ENV DB_HOST=mysql
ENV DB_USERNAME=thrive
ENV DB_PASSWORD=
ENV EMAIL_HOST=mail.qq.com
ENV EMAIL_PORT=465
ENV EMAIL_USERNAME=
ENV EMAIL_PASSWORD=
ENV TZ=Asia/Shanghai

WORKDIR /server

COPY deploy/artifacts/blog.jar /server/app.jar
COPY RUN.runtime.sh /server/RUN.runtime.sh

RUN chmod +x /server/RUN.runtime.sh

EXPOSE 9003

ENTRYPOINT ["/server/RUN.runtime.sh"]
